env: "local"
http_server:
    address: "localhost:3001"
    timeout: 4s
    idle_timeout: 60s
storage:
    db_host: "localhost"
    db_port: 5432
    db_name: "research_info"
    db_username: "postgres"
    db_password: "vuigxuishgbgiufs"
